export const countries = [
  {
    code2: "AD",
    emoji: "🇦🇩",
    unicode: "U+1F1E6 U+1F1E9",
    name: "Andorra",
    dialCode: "+376",
  },
  {
    code2: "AE",
    emoji: "🇦🇪",
    unicode: "U+1F1E6 U+1F1EA",
    name: "United Arab Emirates",
    dialCode: "+971",
  },
  {
    code2: "AF",
    emoji: "🇦🇫",
    unicode: "U+1F1E6 U+1F1EB",
    name: "Afghanistan",
    dialCode: "+93",
  },
  {
    code2: "AG",
    emoji: "🇦🇬",
    unicode: "U+1F1E6 U+1F1EC",
    name: "Antigua and Barbuda",
    dialCode: "+1268",
  },
  {
    code2: "AI",
    emoji: "🇦🇮",
    unicode: "U+1F1E6 U+1F1EE",
    name: "Anguilla",
    dialCode: "+1 264",
  },
  {
    code2: "AL",
    emoji: "🇦🇱",
    unicode: "U+1F1E6 U+1F1F1",
    name: "Albania",
    dialCode: "+355",
  },
  {
    code2: "AM",
    emoji: "🇦🇲",
    unicode: "U+1F1E6 U+1F1F2",
    name: "Armenia",
    dialCode: "+374",
  },
  {
    code2: "AO",
    emoji: "🇦🇴",
    unicode: "U+1F1E6 U+1F1F4",
    name: "Angola",
    dialCode: "+244",
  },
  {
    code2: "AQ",
    emoji: "🇦🇶",
    unicode: "U+1F1E6 U+1F1F6",
    name: "Antarctica",
    dialCode: null,
  },
  {
    code2: "AR",
    emoji: "🇦🇷",
    unicode: "U+1F1E6 U+1F1F7",
    name: "Argentina",
    dialCode: "+54",
  },
  {
    code2: "AS",
    emoji: "🇦🇸",
    unicode: "U+1F1E6 U+1F1F8",
    name: "American Samoa",
    dialCode: "+1 684",
  },
  {
    code2: "AT",
    emoji: "🇦🇹",
    unicode: "U+1F1E6 U+1F1F9",
    name: "Austria",
    dialCode: "+43",
  },
  {
    code2: "AU",
    emoji: "🇦🇺",
    unicode: "U+1F1E6 U+1F1FA",
    name: "Australia",
    dialCode: "+61",
  },
  {
    code2: "AW",
    emoji: "🇦🇼",
    unicode: "U+1F1E6 U+1F1FC",
    name: "Aruba",
    dialCode: "+297",
  },
  {
    code2: "AX",
    emoji: "🇦🇽",
    unicode: "U+1F1E6 U+1F1FD",
    name: "Åland Islands",
    dialCode: "",
  },
  {
    code2: "AZ",
    emoji: "🇦🇿",
    unicode: "U+1F1E6 U+1F1FF",
    name: "Azerbaijan",
    dialCode: "+994",
  },
  {
    code2: "BA",
    emoji: "🇧🇦",
    unicode: "U+1F1E7 U+1F1E6",
    name: "Bosnia-Herzegovina",
    dialCode: "+387",
  },
  {
    code2: "BB",
    emoji: "🇧🇧",
    unicode: "U+1F1E7 U+1F1E7",
    name: "Barbados",
    dialCode: "+1 246",
  },
  {
    code2: "BD",
    emoji: "🇧🇩",
    unicode: "U+1F1E7 U+1F1E9",
    name: "Bangladesh",
    dialCode: "+880",
  },
  {
    code2: "BE",
    emoji: "🇧🇪",
    unicode: "U+1F1E7 U+1F1EA",
    name: "Belgium",
    dialCode: "+32",
  },
  {
    code2: "BF",
    emoji: "🇧🇫",
    unicode: "U+1F1E7 U+1F1EB",
    name: "Burkina Faso",
    dialCode: "+226",
  },
  {
    code2: "BG",
    emoji: "🇧🇬",
    unicode: "U+1F1E7 U+1F1EC",
    name: "Bulgaria",
    dialCode: "+359",
  },
  {
    code2: "BH",
    emoji: "🇧🇭",
    unicode: "U+1F1E7 U+1F1ED",
    name: "Bahrain",
    dialCode: "+973",
  },
  {
    code2: "BI",
    emoji: "🇧🇮",
    unicode: "U+1F1E7 U+1F1EE",
    name: "Burundi",
    dialCode: "+257",
  },
  {
    code2: "BJ",
    emoji: "🇧🇯",
    unicode: "U+1F1E7 U+1F1EF",
    name: "Benin",
    dialCode: "+229",
  },
  {
    code2: "BL",
    emoji: "🇧🇱",
    unicode: "U+1F1E7 U+1F1F1",
    name: "Saint Barthélemy",
    dialCode: "+590",
  },
  {
    code2: "BM",
    emoji: "🇧🇲",
    unicode: "U+1F1E7 U+1F1F2",
    name: "Bermuda",
    dialCode: "+1 441",
  },
  {
    code2: "BN",
    emoji: "🇧🇳",
    unicode: "U+1F1E7 U+1F1F3",
    name: "Brunei Darussalam",
    dialCode: "+673",
  },
  {
    code2: "BO",
    emoji: "🇧🇴",
    unicode: "U+1F1E7 U+1F1F4",
    name: "Bolivia",
    dialCode: "+591",
  },
  {
    code2: "BQ",
    emoji: "🇧🇶",
    unicode: "U+1F1E7 U+1F1F6",
    name: "Bonaire, Sint Eustatius and Saba",
  },
  {
    code2: "BR",
    emoji: "🇧🇷",
    unicode: "U+1F1E7 U+1F1F7",
    name: "Brazil",
    dialCode: "+55",
  },
  {
    code2: "BS",
    emoji: "🇧🇸",
    unicode: "U+1F1E7 U+1F1F8",
    name: "Bahamas",
    dialCode: "+1 242",
  },
  {
    code2: "BT",
    emoji: "🇧🇹",
    unicode: "U+1F1E7 U+1F1F9",
    name: "Bhutan",
    dialCode: "+975",
  },
  {
    code2: "BV",
    emoji: "🇧🇻",
    unicode: "U+1F1E7 U+1F1FB",
    name: "Bouvet Island",
  },
  {
    code2: "BW",
    emoji: "🇧🇼",
    unicode: "U+1F1E7 U+1F1FC",
    name: "Botswana",
    dialCode: "+267",
  },
  {
    code2: "BY",
    emoji: "🇧🇾",
    unicode: "U+1F1E7 U+1F1FE",
    name: "Belarus",
    dialCode: "+375",
  },
  {
    code2: "BZ",
    emoji: "🇧🇿",
    unicode: "U+1F1E7 U+1F1FF",
    name: "Belize",
    dialCode: "+501",
  },
  {
    code2: "CA",
    emoji: "🇨🇦",
    unicode: "U+1F1E8 U+1F1E6",
    name: "Canada",
    dialCode: "+1",
  },
  {
    code2: "CC",
    emoji: "🇨🇨",
    unicode: "U+1F1E8 U+1F1E8",
    name: "Cocos (Keeling) Islands",
    dialCode: "+61",
  },
  {
    code2: "CD",
    emoji: "🇨🇩",
    unicode: "U+1F1E8 U+1F1E9",
    name: "Congo",
    dialCode: "+243",
  },
  {
    code2: "CF",
    emoji: "🇨🇫",
    unicode: "U+1F1E8 U+1F1EB",
    name: "Central African Republic",
    dialCode: "+236",
  },
  {
    code2: "CG",
    emoji: "🇨🇬",
    unicode: "U+1F1E8 U+1F1EC",
    name: "Congo",
    dialCode: "+242",
  },
  {
    code2: "CH",
    emoji: "🇨🇭",
    unicode: "U+1F1E8 U+1F1ED",
    name: "Switzerland",
    dialCode: "+41",
  },
  {
    code2: "CI",
    emoji: "🇨🇮",
    unicode: "U+1F1E8 U+1F1EE",
    name: "Ivory Coast",
    dialCode: "+225",
  },
  {
    code2: "CK",
    emoji: "🇨🇰",
    unicode: "U+1F1E8 U+1F1F0",
    name: "Cook Islands",
    dialCode: "+682",
  },
  {
    code2: "CL",
    emoji: "🇨🇱",
    unicode: "U+1F1E8 U+1F1F1",
    name: "Chile",
    dialCode: "+56",
  },
  {
    code2: "CM",
    emoji: "🇨🇲",
    unicode: "U+1F1E8 U+1F1F2",
    name: "Cameroon",
    dialCode: "+237",
  },
  {
    code2: "CN",
    emoji: "🇨🇳",
    unicode: "U+1F1E8 U+1F1F3",
    name: "China",
    dialCode: "+86",
  },
  {
    code2: "CO",
    emoji: "🇨🇴",
    unicode: "U+1F1E8 U+1F1F4",
    name: "Colombia",
    dialCode: "+57",
  },
  {
    code2: "CR",
    emoji: "🇨🇷",
    unicode: "U+1F1E8 U+1F1F7",
    name: "Costa Rica",
    dialCode: "+506",
  },
  {
    code2: "CU",
    emoji: "🇨🇺",
    unicode: "U+1F1E8 U+1F1FA",
    name: "Cuba",
    dialCode: "+53",
  },
  {
    code2: "CV",
    emoji: "🇨🇻",
    unicode: "U+1F1E8 U+1F1FB",
    name: "Cape Verde",
    dialCode: "+238",
  },
  {
    code2: "CW",
    emoji: "🇨🇼",
    unicode: "U+1F1E8 U+1F1FC",
    name: "Curaçao",
  },
  {
    code2: "CX",
    emoji: "🇨🇽",
    unicode: "U+1F1E8 U+1F1FD",
    name: "Christmas Island",
    dialCode: "+61",
  },
  {
    code2: "CY",
    emoji: "🇨🇾",
    unicode: "U+1F1E8 U+1F1FE",
    name: "Cyprus",
    dialCode: "+537",
  },
  {
    code2: "CZ",
    emoji: "🇨🇿",
    unicode: "U+1F1E8 U+1F1FF",
    name: "Czech Republic",
    dialCode: "+420",
  },
  {
    code2: "DE",
    emoji: "🇩🇪",
    unicode: "U+1F1E9 U+1F1EA",
    name: "Germany",
    dialCode: "+49",
  },
  {
    code2: "DJ",
    emoji: "🇩🇯",
    unicode: "U+1F1E9 U+1F1EF",
    name: "Djibouti",
    dialCode: "+253",
  },
  {
    code2: "DK",
    emoji: "🇩🇰",
    unicode: "U+1F1E9 U+1F1F0",
    name: "Denmark",
    dialCode: "+45",
  },
  {
    code2: "DM",
    emoji: "🇩🇲",
    unicode: "U+1F1E9 U+1F1F2",
    name: "Dominica",
    dialCode: "+1 767",
  },
  {
    code2: "DO",
    emoji: "🇩🇴",
    unicode: "U+1F1E9 U+1F1F4",
    name: "Dominican Republic",
    dialCode: "+1 849",
  },
  {
    code2: "DZ",
    emoji: "🇩🇿",
    unicode: "U+1F1E9 U+1F1FF",
    name: "Algeria",
    dialCode: "+213",
  },
  {
    code2: "EC",
    emoji: "🇪🇨",
    unicode: "U+1F1EA U+1F1E8",
    name: "Ecuador",
    dialCode: "+593",
  },
  {
    code2: "EE",
    emoji: "🇪🇪",
    unicode: "U+1F1EA U+1F1EA",
    name: "Estonia",
    dialCode: "+372",
  },
  {
    code2: "EG",
    emoji: "🇪🇬",
    unicode: "U+1F1EA U+1F1EC",
    name: "Egypt",
    dialCode: "+20",
  },
  {
    code2: "EH",
    emoji: "🇪🇭",
    unicode: "U+1F1EA U+1F1ED",
    name: "Western Sahara",
  },
  {
    code2: "ER",
    emoji: "🇪🇷",
    unicode: "U+1F1EA U+1F1F7",
    name: "Eritrea",
    dialCode: "+291",
  },
  {
    code2: "ES",
    emoji: "🇪🇸",
    unicode: "U+1F1EA U+1F1F8",
    name: "Spain",
    dialCode: "+34",
  },
  {
    code2: "ET",
    emoji: "🇪🇹",
    unicode: "U+1F1EA U+1F1F9",
    name: "Ethiopia",
    dialCode: "+251",
  },
  {
    code2: "EU",
    emoji: "🇪🇺",
    unicode: "U+1F1EA U+1F1FA",
    name: "European Union",
  },
  {
    code2: "FI",
    emoji: "🇫🇮",
    unicode: "U+1F1EB U+1F1EE",
    name: "Finland",
    dialCode: "+358",
  },
  {
    code2: "FJ",
    emoji: "🇫🇯",
    unicode: "U+1F1EB U+1F1EF",
    name: "Fiji",
    dialCode: "+679",
  },
  {
    code2: "FK",
    emoji: "🇫🇰",
    unicode: "U+1F1EB U+1F1F0",
    name: "Falkland Islands (Malvinas)",
    dialCode: "+500",
  },
  {
    code2: "FM",
    emoji: "🇫🇲",
    unicode: "U+1F1EB U+1F1F2",
    name: "Micronesia",
    dialCode: "+691",
  },
  {
    code2: "FO",
    emoji: "🇫🇴",
    unicode: "U+1F1EB U+1F1F4",
    name: "Faroe Islands",
    dialCode: "+298",
  },
  {
    code2: "FR",
    emoji: "🇫🇷",
    unicode: "U+1F1EB U+1F1F7",
    name: "France",
    dialCode: "+33",
  },
  {
    code2: "GA",
    emoji: "🇬🇦",
    unicode: "U+1F1EC U+1F1E6",
    name: "Gabon",
    dialCode: "+241",
  },
  {
    code2: "GB",
    emoji: "🇬🇧",
    unicode: "U+1F1EC U+1F1E7",
    name: "UK",
    dialCode: "+44",
  },
  {
    code2: "GD",
    emoji: "🇬🇩",
    unicode: "U+1F1EC U+1F1E9",
    name: "Grenada",
    dialCode: "+1 473",
  },
  {
    code2: "GE",
    emoji: "🇬🇪",
    unicode: "U+1F1EC U+1F1EA",
    name: "Georgia",
    dialCode: "+995",
  },
  {
    code2: "GF",
    emoji: "🇬🇫",
    unicode: "U+1F1EC U+1F1EB",
    name: "French Guiana",
    dialCode: "+594",
  },
  {
    code2: "GG",
    emoji: "🇬🇬",
    unicode: "U+1F1EC U+1F1EC",
    name: "Guernsey",
    dialCode: "+44",
  },
  {
    code2: "GH",
    emoji: "🇬🇭",
    unicode: "U+1F1EC U+1F1ED",
    name: "Ghana",
    dialCode: "+233",
  },
  {
    code2: "GI",
    emoji: "🇬🇮",
    unicode: "U+1F1EC U+1F1EE",
    name: "Gibraltar",
    dialCode: "+350",
  },
  {
    code2: "GL",
    emoji: "🇬🇱",
    unicode: "U+1F1EC U+1F1F1",
    name: "Greenland",
    dialCode: "+299",
  },
  {
    code2: "GM",
    emoji: "🇬🇲",
    unicode: "U+1F1EC U+1F1F2",
    name: "Gambia",
    dialCode: "+220",
  },
  {
    code2: "GN",
    emoji: "🇬🇳",
    unicode: "U+1F1EC U+1F1F3",
    name: "Guinea",
    dialCode: "+224",
  },
  {
    code2: "GP",
    emoji: "🇬🇵",
    unicode: "U+1F1EC U+1F1F5",
    name: "Guadeloupe",
    dialCode: "+590",
  },
  {
    code2: "GQ",
    emoji: "🇬🇶",
    unicode: "U+1F1EC U+1F1F6",
    name: "Equatorial Guinea",
    dialCode: "+240",
  },
  {
    code2: "GR",
    emoji: "🇬🇷",
    unicode: "U+1F1EC U+1F1F7",
    name: "Greece",
    dialCode: "+30",
  },
  {
    code2: "GS",
    emoji: "🇬🇸",
    unicode: "U+1F1EC U+1F1F8",
    name: "South Georgia",
    dialCode: "+500",
  },
  {
    code2: "GT",
    emoji: "🇬🇹",
    unicode: "U+1F1EC U+1F1F9",
    name: "Guatemala",
    dialCode: "+502",
  },
  {
    code2: "GU",
    emoji: "🇬🇺",
    unicode: "U+1F1EC U+1F1FA",
    name: "Guam",
    dialCode: "+1 671",
  },
  {
    code2: "GW",
    emoji: "🇬🇼",
    unicode: "U+1F1EC U+1F1FC",
    name: "Guinea-Bissau",
    dialCode: "+245",
  },
  {
    code2: "GY",
    emoji: "🇬🇾",
    unicode: "U+1F1EC U+1F1FE",
    name: "Guyana",
    dialCode: "+595",
  },
  {
    code2: "HK",
    emoji: "🇭🇰",
    unicode: "U+1F1ED U+1F1F0",
    name: "Hong Kong",
    dialCode: "+852",
  },
  {
    code2: "HM",
    emoji: "🇭🇲",
    unicode: "U+1F1ED U+1F1F2",
    name: "Heard Island and Mcdonald Islands",
  },
  {
    code2: "HN",
    emoji: "🇭🇳",
    unicode: "U+1F1ED U+1F1F3",
    name: "Honduras",
    dialCode: "+504",
  },
  {
    code2: "HR",
    emoji: "🇭🇷",
    unicode: "U+1F1ED U+1F1F7",
    name: "Croatia",
    dialCode: "+385",
  },
  {
    code2: "HT",
    emoji: "🇭🇹",
    unicode: "U+1F1ED U+1F1F9",
    name: "Haiti",
    dialCode: "+509",
  },
  {
    code2: "HU",
    emoji: "🇭🇺",
    unicode: "U+1F1ED U+1F1FA",
    name: "Hungary",
    dialCode: "+36",
  },
  {
    code2: "ID",
    emoji: "🇮🇩",
    unicode: "U+1F1EE U+1F1E9",
    name: "Indonesia",
    dialCode: "+62",
  },
  {
    code2: "IE",
    emoji: "🇮🇪",
    unicode: "U+1F1EE U+1F1EA",
    name: "Ireland",
    dialCode: "+353",
  },
  {
    code2: "IL",
    emoji: "🇮🇱",
    unicode: "U+1F1EE U+1F1F1",
    name: "Israel",
    dialCode: "+972",
  },
  {
    code2: "IM",
    emoji: "🇮🇲",
    unicode: "U+1F1EE U+1F1F2",
    name: "Isle of Man",
    dialCode: "+44",
  },
  {
    code2: "IN",
    emoji: "🇮🇳",
    unicode: "U+1F1EE U+1F1F3",
    name: "India",
    dialCode: "+91",
  },
  {
    code2: "IO",
    emoji: "🇮🇴",
    unicode: "U+1F1EE U+1F1F4",
    name: "British Indian Ocean Territory",
    dialCode: "+246",
  },
  {
    code2: "IQ",
    emoji: "🇮🇶",
    unicode: "U+1F1EE U+1F1F6",
    name: "Iraq",
    dialCode: "+964",
  },
  {
    code2: "IR",
    emoji: "🇮🇷",
    unicode: "U+1F1EE U+1F1F7",
    name: "Iran",
    dialCode: "+98",
  },
  {
    code2: "IS",
    emoji: "🇮🇸",
    unicode: "U+1F1EE U+1F1F8",
    name: "Iceland",
    dialCode: "+354",
  },
  {
    code2: "IT",
    emoji: "🇮🇹",
    unicode: "U+1F1EE U+1F1F9",
    name: "Italy",
    dialCode: "+39",
  },
  {
    code2: "JE",
    emoji: "🇯🇪",
    unicode: "U+1F1EF U+1F1EA",
    name: "Jersey",
    dialCode: "+44",
  },
  {
    code2: "JM",
    emoji: "🇯🇲",
    unicode: "U+1F1EF U+1F1F2",
    name: "Jamaica",
    dialCode: "+1 876",
  },
  {
    code2: "JO",
    emoji: "🇯🇴",
    unicode: "U+1F1EF U+1F1F4",
    name: "Jordan",
    dialCode: "+962",
  },
  {
    code2: "JP",
    emoji: "🇯🇵",
    unicode: "U+1F1EF U+1F1F5",
    name: "Japan",
    dialCode: "+81",
  },
  {
    code2: "KE",
    emoji: "🇰🇪",
    unicode: "U+1F1F0 U+1F1EA",
    name: "Kenya",
    dialCode: "+254",
  },
  {
    code2: "KG",
    emoji: "🇰🇬",
    unicode: "U+1F1F0 U+1F1EC",
    name: "Kyrgyzstan",
    dialCode: "+996",
  },
  {
    code2: "KH",
    emoji: "🇰🇭",
    unicode: "U+1F1F0 U+1F1ED",
    name: "Cambodia",
    dialCode: "+855",
  },
  {
    code2: "KI",
    emoji: "🇰🇮",
    unicode: "U+1F1F0 U+1F1EE",
    name: "Kiribati",
    dialCode: "+686",
  },
  {
    code2: "KM",
    emoji: "🇰🇲",
    unicode: "U+1F1F0 U+1F1F2",
    name: "Comoros",
    dialCode: "+269",
  },
  {
    code2: "KN",
    emoji: "🇰🇳",
    unicode: "U+1F1F0 U+1F1F3",
    name: "Saint Kitts and Nevis",
    dialCode: "+1 869",
  },
  {
    code2: "KP",
    emoji: "🇰🇵",
    unicode: "U+1F1F0 U+1F1F5",
    name: "North Korea",
    dialCode: "+850",
  },
  {
    code2: "KR",
    emoji: "🇰🇷",
    unicode: "U+1F1F0 U+1F1F7",
    name: "South Korea",
    dialCode: "+82",
  },
  {
    code2: "KW",
    emoji: "🇰🇼",
    unicode: "U+1F1F0 U+1F1FC",
    name: "Kuwait",
    dialCode: "+965",
  },
  {
    code2: "KY",
    emoji: "🇰🇾",
    unicode: "U+1F1F0 U+1F1FE",
    name: "Cayman Islands",
    dialCode: "+ 345",
  },
  {
    code2: "KZ",
    emoji: "🇰🇿",
    unicode: "U+1F1F0 U+1F1FF",
    name: "Kazakhstan",
    dialCode: "+7 7",
  },
  {
    code2: "LA",
    emoji: "🇱🇦",
    unicode: "U+1F1F1 U+1F1E6",
    name: "Lao People's Democratic Republic",
    dialCode: "+856",
  },
  {
    code2: "LB",
    emoji: "🇱🇧",
    unicode: "U+1F1F1 U+1F1E7",
    name: "Lebanon",
    dialCode: "+961",
  },
  {
    code2: "LC",
    emoji: "🇱🇨",
    unicode: "U+1F1F1 U+1F1E8",
    name: "Saint Lucia",
    dialCode: "+1 758",
  },
  {
    code2: "LI",
    emoji: "🇱🇮",
    unicode: "U+1F1F1 U+1F1EE",
    name: "Liechtenstein",
    dialCode: "+423",
  },
  {
    code2: "LK",
    emoji: "🇱🇰",
    unicode: "U+1F1F1 U+1F1F0",
    name: "Sri Lanka",
    dialCode: "+94",
  },
  {
    code2: "LR",
    emoji: "🇱🇷",
    unicode: "U+1F1F1 U+1F1F7",
    name: "Liberia",
    dialCode: "+231",
  },
  {
    code2: "LS",
    emoji: "🇱🇸",
    unicode: "U+1F1F1 U+1F1F8",
    name: "Lesotho",
    dialCode: "+266",
  },
  {
    code2: "LT",
    emoji: "🇱🇹",
    unicode: "U+1F1F1 U+1F1F9",
    name: "Lithuania",
    dialCode: "+370",
  },
  {
    code2: "LU",
    emoji: "🇱🇺",
    unicode: "U+1F1F1 U+1F1FA",
    name: "Luxembourg",
    dialCode: "+352",
  },
  {
    code2: "LV",
    emoji: "🇱🇻",
    unicode: "U+1F1F1 U+1F1FB",
    name: "Latvia",
    dialCode: "+371",
  },
  {
    code2: "LY",
    emoji: "🇱🇾",
    unicode: "U+1F1F1 U+1F1FE",
    name: "Libya",
    dialCode: "+218",
  },
  {
    code2: "MA",
    emoji: "🇲🇦",
    unicode: "U+1F1F2 U+1F1E6",
    name: "Morocco",
    dialCode: "+212",
  },
  {
    code2: "MC",
    emoji: "🇲🇨",
    unicode: "U+1F1F2 U+1F1E8",
    name: "Monaco",
    dialCode: "+377",
  },
  {
    code2: "MD",
    emoji: "🇲🇩",
    unicode: "U+1F1F2 U+1F1E9",
    name: "Moldova",
    dialCode: "+373",
  },
  {
    code2: "ME",
    emoji: "🇲🇪",
    unicode: "U+1F1F2 U+1F1EA",
    name: "Montenegro",
    dialCode: "+382",
  },
  {
    code2: "MF",
    emoji: "🇲🇫",
    unicode: "U+1F1F2 U+1F1EB",
    name: "Saint Martin (French Part)",
    dialCode: "+590",
  },
  {
    code2: "MG",
    emoji: "🇲🇬",
    unicode: "U+1F1F2 U+1F1EC",
    name: "Madagascar",
    dialCode: "+261",
  },
  {
    code2: "MH",
    emoji: "🇲🇭",
    unicode: "U+1F1F2 U+1F1ED",
    name: "Marshall Islands",
    dialCode: "+692",
  },
  {
    code2: "MK",
    emoji: "🇲🇰",
    unicode: "U+1F1F2 U+1F1F0",
    name: "Macedonia",
    dialCode: "+389",
  },
  {
    code2: "ML",
    emoji: "🇲🇱",
    unicode: "U+1F1F2 U+1F1F1",
    name: "Mali",
    dialCode: "+223",
  },
  {
    code2: "MM",
    emoji: "🇲🇲",
    unicode: "U+1F1F2 U+1F1F2",
    name: "Burma",
    dialCode: "+95",
  },
  {
    code2: "MN",
    emoji: "🇲🇳",
    unicode: "U+1F1F2 U+1F1F3",
    name: "Mongolia",
    dialCode: "+976",
  },
  {
    code2: "MO",
    emoji: "🇲🇴",
    unicode: "U+1F1F2 U+1F1F4",
    name: "Macao",
    dialCode: "+853",
  },
  {
    code2: "MP",
    emoji: "🇲🇵",
    unicode: "U+1F1F2 U+1F1F5",
    name: "Northern Mariana Islands",
    dialCode: "+1 670",
  },
  {
    code2: "MQ",
    emoji: "🇲🇶",
    unicode: "U+1F1F2 U+1F1F6",
    name: "Martinique",
    dialCode: "+596",
  },
  {
    code2: "MR",
    emoji: "🇲🇷",
    unicode: "U+1F1F2 U+1F1F7",
    name: "Mauritania",
    dialCode: "+222",
  },
  {
    code2: "MS",
    emoji: "🇲🇸",
    unicode: "U+1F1F2 U+1F1F8",
    name: "Montserrat",
    dialCode: "+1664",
  },
  {
    code2: "MT",
    emoji: "🇲🇹",
    unicode: "U+1F1F2 U+1F1F9",
    name: "Malta",
    dialCode: "+356",
  },
  {
    code2: "MU",
    emoji: "🇲🇺",
    unicode: "U+1F1F2 U+1F1FA",
    name: "Mauritius",
    dialCode: "+230",
  },
  {
    code2: "MV",
    emoji: "🇲🇻",
    unicode: "U+1F1F2 U+1F1FB",
    name: "Maldives",
    dialCode: "+960",
  },
  {
    code2: "MW",
    emoji: "🇲🇼",
    unicode: "U+1F1F2 U+1F1FC",
    name: "Malawi",
    dialCode: "+265",
  },
  {
    code2: "MX",
    emoji: "🇲🇽",
    unicode: "U+1F1F2 U+1F1FD",
    name: "Mexico",
    dialCode: "+52",
  },
  {
    code2: "MY",
    emoji: "🇲🇾",
    unicode: "U+1F1F2 U+1F1FE",
    name: "Malaysia",
    dialCode: "+60",
  },
  {
    code2: "MZ",
    emoji: "🇲🇿",
    unicode: "U+1F1F2 U+1F1FF",
    name: "Mozambique",
    dialCode: "+258",
  },
  {
    code2: "NA",
    emoji: "🇳🇦",
    unicode: "U+1F1F3 U+1F1E6",
    name: "Namibia",
    dialCode: "+264",
  },
  {
    code2: "NC",
    emoji: "🇳🇨",
    unicode: "U+1F1F3 U+1F1E8",
    name: "New Caledonia",
    dialCode: "+687",
  },
  {
    code2: "NE",
    emoji: "🇳🇪",
    unicode: "U+1F1F3 U+1F1EA",
    name: "Niger",
    dialCode: "+227",
  },
  {
    code2: "NF",
    emoji: "🇳🇫",
    unicode: "U+1F1F3 U+1F1EB",
    name: "Norfolk Island",
    dialCode: "+672",
  },
  {
    code2: "NG",
    emoji: "🇳🇬",
    unicode: "U+1F1F3 U+1F1EC",
    name: "Nigeria",
    dialCode: "+234",
  },
  {
    code2: "NI",
    emoji: "🇳🇮",
    unicode: "U+1F1F3 U+1F1EE",
    name: "Nicaragua",
    dialCode: "+505",
  },
  {
    code2: "NL",
    emoji: "🇳🇱",
    unicode: "U+1F1F3 U+1F1F1",
    name: "Netherlands",
    dialCode: "+31",
  },
  {
    code2: "NO",
    emoji: "🇳🇴",
    unicode: "U+1F1F3 U+1F1F4",
    name: "Norway",
    dialCode: "+47",
  },
  {
    code2: "NP",
    emoji: "🇳🇵",
    unicode: "U+1F1F3 U+1F1F5",
    name: "Nepal",
    dialCode: "+977",
  },
  {
    code2: "NR",
    emoji: "🇳🇷",
    unicode: "U+1F1F3 U+1F1F7",
    name: "Nauru",
    dialCode: "+674",
  },
  {
    code2: "NU",
    emoji: "🇳🇺",
    unicode: "U+1F1F3 U+1F1FA",
    name: "Niue",
    dialCode: "+683",
  },
  {
    code2: "NZ",
    emoji: "🇳🇿",
    unicode: "U+1F1F3 U+1F1FF",
    name: "New Zealand",
    dialCode: "+64",
  },
  {
    code2: "OM",
    emoji: "🇴🇲",
    unicode: "U+1F1F4 U+1F1F2",
    name: "Oman",
    dialCode: "+968",
  },
  {
    code2: "PA",
    emoji: "🇵🇦",
    unicode: "U+1F1F5 U+1F1E6",
    name: "Panama",
    dialCode: "+507",
  },
  {
    code2: "PE",
    emoji: "🇵🇪",
    unicode: "U+1F1F5 U+1F1EA",
    name: "Peru",
    dialCode: "+51",
  },
  {
    code2: "PF",
    emoji: "🇵🇫",
    unicode: "U+1F1F5 U+1F1EB",
    name: "French Polynesia",
    dialCode: "+689",
  },
  {
    code2: "PG",
    emoji: "🇵🇬",
    unicode: "U+1F1F5 U+1F1EC",
    name: "Papua New Guinea",
    dialCode: "+675",
  },
  {
    code2: "PH",
    emoji: "🇵🇭",
    unicode: "U+1F1F5 U+1F1ED",
    name: "Philippines",
    dialCode: "+63",
  },
  {
    code2: "PK",
    emoji: "🇵🇰",
    unicode: "U+1F1F5 U+1F1F0",
    name: "Pakistan",
    dialCode: "+92",
  },
  {
    code2: "PL",
    emoji: "🇵🇱",
    unicode: "U+1F1F5 U+1F1F1",
    name: "Poland",
    dialCode: "+48",
  },
  {
    code2: "PM",
    emoji: "🇵🇲",
    unicode: "U+1F1F5 U+1F1F2",
    name: "Saint Pierre and Miquelon",
    dialCode: "+508",
  },
  {
    code2: "PN",
    emoji: "🇵🇳",
    unicode: "U+1F1F5 U+1F1F3",
    name: "Pitcairn",
    dialCode: "+872",
  },
  {
    code2: "PR",
    emoji: "🇵🇷",
    unicode: "U+1F1F5 U+1F1F7",
    name: "Puerto Rico",
    dialCode: "+1 939",
  },
  {
    code2: "PS",
    emoji: "🇵🇸",
    unicode: "U+1F1F5 U+1F1F8",
    name: "Palestinian Territory",
    dialCode: "+970",
  },
  {
    code2: "PT",
    emoji: "🇵🇹",
    unicode: "U+1F1F5 U+1F1F9",
    name: "Portugal",
    dialCode: "+351",
  },
  {
    code2: "PW",
    emoji: "🇵🇼",
    unicode: "U+1F1F5 U+1F1FC",
    name: "Palau",
    dialCode: "+680",
  },
  {
    code2: "PY",
    emoji: "🇵🇾",
    unicode: "U+1F1F5 U+1F1FE",
    name: "Paraguay",
    dialCode: "+595",
  },
  {
    code2: "QA",
    emoji: "🇶🇦",
    unicode: "U+1F1F6 U+1F1E6",
    name: "Qatar",
    dialCode: "+974",
  },
  {
    code2: "RE",
    emoji: "🇷🇪",
    unicode: "U+1F1F7 U+1F1EA",
    name: "Réunion",
    dialCode: "+262",
  },
  {
    code2: "RO",
    emoji: "🇷🇴",
    unicode: "U+1F1F7 U+1F1F4",
    name: "Romania",
    dialCode: "+40",
  },
  {
    code2: "RS",
    emoji: "🇷🇸",
    unicode: "U+1F1F7 U+1F1F8",
    name: "Serbia",
    dialCode: "+381",
  },
  {
    code2: "RU",
    emoji: "🇷🇺",
    unicode: "U+1F1F7 U+1F1FA",
    name: "Russia",
    dialCode: "+7",
  },
  {
    code2: "RW",
    emoji: "🇷🇼",
    unicode: "U+1F1F7 U+1F1FC",
    name: "Rwanda",
    dialCode: "+250",
  },
  {
    code2: "SA",
    emoji: "🇸🇦",
    unicode: "U+1F1F8 U+1F1E6",
    name: "Saudi Arabia",
    dialCode: "+966",
  },
  {
    code2: "SB",
    emoji: "🇸🇧",
    unicode: "U+1F1F8 U+1F1E7",
    name: "Solomon Islands",
    dialCode: "+677",
  },
  {
    code2: "SC",
    emoji: "🇸🇨",
    unicode: "U+1F1F8 U+1F1E8",
    name: "Seychelles",
    dialCode: "+248",
  },
  {
    code2: "SD",
    emoji: "🇸🇩",
    unicode: "U+1F1F8 U+1F1E9",
    name: "Sudan",
    dialCode: "+249",
  },
  {
    code2: "SE",
    emoji: "🇸🇪",
    unicode: "U+1F1F8 U+1F1EA",
    name: "Sweden",
    dialCode: "+46",
  },
  {
    code2: "SG",
    emoji: "🇸🇬",
    unicode: "U+1F1F8 U+1F1EC",
    name: "Singapore",
    dialCode: "+65",
  },
  {
    code2: "SH",
    emoji: "🇸🇭",
    unicode: "U+1F1F8 U+1F1ED",
    name: "Saint Helena, Ascension and Tristan Da Cunha",
    dialCode: "+290",
  },
  {
    code2: "SI",
    emoji: "🇸🇮",
    unicode: "U+1F1F8 U+1F1EE",
    name: "Slovenia",
    dialCode: "+386",
  },
  {
    code2: "SJ",
    emoji: "🇸🇯",
    unicode: "U+1F1F8 U+1F1EF",
    name: "Svalbard and Jan Mayen",
    dialCode: "+47",
  },
  {
    code2: "SK",
    emoji: "🇸🇰",
    unicode: "U+1F1F8 U+1F1F0",
    name: "Slovakia",
    dialCode: "+421",
  },
  {
    code2: "SL",
    emoji: "🇸🇱",
    unicode: "U+1F1F8 U+1F1F1",
    name: "Sierra Leone",
    dialCode: "+232",
  },
  {
    code2: "SM",
    emoji: "🇸🇲",
    unicode: "U+1F1F8 U+1F1F2",
    name: "San Marino",
    dialCode: "+378",
  },
  {
    code2: "SN",
    emoji: "🇸🇳",
    unicode: "U+1F1F8 U+1F1F3",
    name: "Sénégal",
    dialCode: "+221",
  },
  {
    code2: "SO",
    emoji: "🇸🇴",
    unicode: "U+1F1F8 U+1F1F4",
    name: "Somalia",
    dialCode: "+252",
  },
  {
    code2: "SR",
    emoji: "🇸🇷",
    unicode: "U+1F1F8 U+1F1F7",
    name: "Suriname",
    dialCode: "+597",
  },
  {
    code2: "SS",
    emoji: "🇸🇸",
    unicode: "U+1F1F8 U+1F1F8",
    name: "South Sudan",
  },
  {
    code2: "ST",
    emoji: "🇸🇹",
    unicode: "U+1F1F8 U+1F1F9",
    name: "Sao Tome and Principe",
    dialCode: "+239",
  },
  {
    code2: "SV",
    emoji: "🇸🇻",
    unicode: "U+1F1F8 U+1F1FB",
    name: "El Salvador",
    dialCode: "+503",
  },
  {
    code2: "SX",
    emoji: "🇸🇽",
    unicode: "U+1F1F8 U+1F1FD",
    name: "Sint Maarten (Dutch Part)",
  },
  {
    code2: "SY",
    emoji: "🇸🇾",
    unicode: "U+1F1F8 U+1F1FE",
    name: "Syrian Arab Republic",
    dialCode: "+963",
  },
  {
    code2: "SZ",
    emoji: "🇸🇿",
    unicode: "U+1F1F8 U+1F1FF",
    name: "Swaziland",
    dialCode: "+268",
  },
  {
    code2: "TC",
    emoji: "🇹🇨",
    unicode: "U+1F1F9 U+1F1E8",
    name: "Turks and Caicos Islands",
    dialCode: "+1 649",
  },
  {
    code2: "TD",
    emoji: "🇹🇩",
    unicode: "U+1F1F9 U+1F1E9",
    name: "Chad",
    dialCode: "+235",
  },
  {
    code2: "TF",
    emoji: "🇹🇫",
    unicode: "U+1F1F9 U+1F1EB",
    name: "French Southern Territories",
  },
  {
    code2: "TG",
    emoji: "🇹🇬",
    unicode: "U+1F1F9 U+1F1EC",
    name: "Togo",
    dialCode: "+228",
  },
  {
    code2: "TH",
    emoji: "🇹🇭",
    unicode: "U+1F1F9 U+1F1ED",
    name: "Thailand",
    dialCode: "+66",
  },
  {
    code2: "TJ",
    emoji: "🇹🇯",
    unicode: "U+1F1F9 U+1F1EF",
    name: "Tajikistan",
    dialCode: "+992",
  },
  {
    code2: "TK",
    emoji: "🇹🇰",
    unicode: "U+1F1F9 U+1F1F0",
    name: "Tokelau",
    dialCode: "+690",
  },
  {
    code2: "TL",
    emoji: "🇹🇱",
    unicode: "U+1F1F9 U+1F1F1",
    name: "Timor-Leste",
    dialCode: "+670",
  },
  {
    code2: "TM",
    emoji: "🇹🇲",
    unicode: "U+1F1F9 U+1F1F2",
    name: "Turkmenistan",
    dialCode: "+993",
  },
  {
    code2: "TN",
    emoji: "🇹🇳",
    unicode: "U+1F1F9 U+1F1F3",
    name: "Tunisia",
    dialCode: "+216",
  },
  {
    code2: "TO",
    emoji: "🇹🇴",
    unicode: "U+1F1F9 U+1F1F4",
    name: "Tonga",
    dialCode: "+676",
  },
  {
    code2: "TR",
    emoji: "🇹🇷",
    unicode: "U+1F1F9 U+1F1F7",
    name: "Turkey",
    dialCode: "+90",
  },
  {
    code2: "TT",
    emoji: "🇹🇹",
    unicode: "U+1F1F9 U+1F1F9",
    name: "Trinidad and Tobago",
    dialCode: "+1 868",
  },
  {
    code2: "TV",
    emoji: "🇹🇻",
    unicode: "U+1F1F9 U+1F1FB",
    name: "Tuvalu",
    dialCode: "+688",
  },
  {
    code2: "TW",
    emoji: "🇹🇼",
    unicode: "U+1F1F9 U+1F1FC",
    name: "Taiwan",
    dialCode: "+886",
  },
  {
    code2: "TZ",
    emoji: "🇹🇿",
    unicode: "U+1F1F9 U+1F1FF",
    name: "Tanzania",
    dialCode: "+255",
  },
  {
    code2: "UA",
    emoji: "🇺🇦",
    unicode: "U+1F1FA U+1F1E6",
    name: "Ukraine",
    dialCode: "+380",
  },
  {
    code2: "UG",
    emoji: "🇺🇬",
    unicode: "U+1F1FA U+1F1EC",
    name: "Uganda",
    dialCode: "+256",
  },
  {
    code2: "UM",
    emoji: "🇺🇲",
    unicode: "U+1F1FA U+1F1F2",
    name: "United States Minor Outlying Islands",
  },
  {
    code2: "US",
    emoji: "🇺🇸",
    unicode: "U+1F1FA U+1F1F8",
    name: "United States",
    dialCode: "+1",
  },
  {
    code2: "UY",
    emoji: "🇺🇾",
    unicode: "U+1F1FA U+1F1FE",
    name: "Uruguay",
    dialCode: "+598",
  },
  {
    code2: "UZ",
    emoji: "🇺🇿",
    unicode: "U+1F1FA U+1F1FF",
    name: "Uzbekistan",
    dialCode: "+998",
  },
  {
    code2: "VA",
    emoji: "🇻🇦",
    unicode: "U+1F1FB U+1F1E6",
    name: "Vatican City",
    dialCode: "+379",
  },
  {
    code2: "VC",
    emoji: "🇻🇨",
    unicode: "U+1F1FB U+1F1E8",
    name: "Saint Vincent and The Grenadines",
    dialCode: "+1 784",
  },
  {
    code2: "VE",
    emoji: "🇻🇪",
    unicode: "U+1F1FB U+1F1EA",
    name: "Venezuela",
    dialCode: "+58",
  },
  {
    code2: "VG",
    emoji: "🇻🇬",
    unicode: "U+1F1FB U+1F1EC",
    name: "Virgin Islands, British",
    dialCode: "+1 284",
  },
  {
    code2: "VI",
    emoji: "🇻🇮",
    unicode: "U+1F1FB U+1F1EE",
    name: "Virgin Islands, U.S.",
    dialCode: "+1 340",
  },
  {
    code2: "VN",
    emoji: "🇻🇳",
    unicode: "U+1F1FB U+1F1F3",
    name: "Viet Nam",
    dialCode: "+84",
  },
  {
    code2: "VU",
    emoji: "🇻🇺",
    unicode: "U+1F1FB U+1F1FA",
    name: "Vanuatu",
    dialCode: "+678",
  },
  {
    code2: "WF",
    emoji: "🇼🇫",
    unicode: "U+1F1FC U+1F1EB",
    name: "Wallis and Futuna",
    dialCode: "+681",
  },
  {
    code2: "WS",
    emoji: "🇼🇸",
    unicode: "U+1F1FC U+1F1F8",
    name: "Samoa",
    dialCode: "+685",
  },
  {
    code2: "XK",
    emoji: "🇽🇰",
    unicode: "U+1F1FD U+1F1F0",
    name: "Kosovo",
    dialCode: "+383",
  },
  {
    code2: "YE",
    emoji: "🇾🇪",
    unicode: "U+1F1FE U+1F1EA",
    name: "Yemen",
    dialCode: "+967",
  },
  {
    code2: "YT",
    emoji: "🇾🇹",
    unicode: "U+1F1FE U+1F1F9",
    name: "Mayotte",
    dialCode: "+262",
  },
  {
    code2: "ZA",
    emoji: "🇿🇦",
    unicode: "U+1F1FF U+1F1E6",
    name: "South Africa",
    dialCode: "+27",
  },
  {
    code2: "ZM",
    emoji: "🇿🇲",
    unicode: "U+1F1FF U+1F1F2",
    name: "Zambia",
    dialCode: "+260",
  },
  {
    code2: "ZW",
    emoji: "🇿🇼",
    unicode: "U+1F1FF U+1F1FC",
    name: "Zimbabwe",
    dialCode: "+263",
  },
];
